In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [3]:
df.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [4]:
# Find employee details whose salary is more than 16000.
filter_salary = df['SALARY'] > 16000
df[filter_salary]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0

In [5]:
# select * from employees where salary > 16000;
filter_salary = df[df['SALARY'] > 16000][['FIRST_NAME', 'LAST_NAME', 'SALARY']]
filter_salary

  FIRST_NAME LAST_NAME  SALARY
0     Steven      King   24000
1      Neena   Kochhar   17000
2        Lex   De Haan   17000

In [6]:
# Find all details of employees whose salary is in range of 10000 to 15000.
emp_salary =  df[(df['SALARY'] > 10000) & (df['SALARY'] < 15000)]
# emp_salary

In [7]:
emp_salary_between = df[df['SALARY'].between(10000, 15000)]
# emp_salary_between

In [9]:
# to check unique values
df['JOB_ID'].unique()

array(['AD_PRES', 'AD_VP', 'IT_PROG', 'FI_MGR', 'FI_ACCOUNT', 'PU_MAN',
       'PU_CLERK', 'ST_MAN', 'ST_CLERK', 'SA_MAN', 'SA_REP', 'SH_CLERK',
       'AD_ASST', 'MK_MAN', 'MK_REP', 'HR_REP', 'PR_REP', 'AC_MGR',
       'AC_ACCOUNT'], dtype=object)

In [15]:
# Find details of employees who works in Job AD_VP and IT_PROG
emp_job = df[(df['JOB_ID'] == 'AD_VP') | (df['JOB_ID'] == 'IT_PROG')]
# emp_job

In [14]:
emp_job_in = df[df['JOB_ID'].isin(['AD_VP', 'IT_PROG'])]
# emp_job_in

In [16]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [19]:
# Find details of employees who works under job IT_PROG and SA_MAN and whose salary is in range of 4000 to 7000.
emp_details = df[
    ((df['JOB_ID'] == 'IT_PROG') | (df['JOB_ID'] == 'SA_REP')) & ((df['SALARY'] >= 4000) & (df['SALARY'] <= 7000))
]
emp_details

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,5/24/2007,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0