In [ ]:
'''
Data Cleaning
--------------
1. Handle Null Values
    a. Fill Null Values
        - .fillna()

        - If data is continuous
            - Mean
            - Median

            1. If mean and median value of a column is equal or almost equal -> fill mean value
            2. Skewness -> .skew()
                - Right Skewness / Positive Skewness
                    -> data_skew > 0.5 -> fill median value
                    
                - Left Skewness / Negative Skewness
                    -> data_skew < 0 -> fill median value
                
                - Normal Distribution / Bell Curve
                    - 0 - 0.5 -> fill mean value

        - If data is discrete / categorical
            - Mode

        - If data is continuous / discrete / categorical
            - Custom Record
        
    b. Drop Null Values
        - .dropna()

2. Drop Duplicate Values
    - Find duplicate records
        - .duplicated()

    - Drop duplicate records
        - .drop_duplicates()

3. Remove unwated data
    a. Remove whitespaces
        - .str.strip()

    b. Remove unwated values (regular expressions, text, digits)
        - .str.replace()

'''

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset/Employees.csv')
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB

In [4]:
# Check number of null values in columns
# df.isnull().sum().sum() # calculate total number of null values of entire data
df.isnull().sum() # calculate total number of null values of each column

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

## Drop Null Values

In [5]:
'''
- To change data permanently
    - inplace(True/False(default))

- Arguments
-------------
    - axis = 1 (column) / 0 (row -> default)
    - how = any(default) / all
    - inplace = (True / False(default))
'''

'\n- To change data permanently\n    - inplace(True/False(default))\n\n- Arguments\n-------------\n    - axis = 1 (column) / 0 (row -> default)\n    - how = any(default) / all\n    - inplace = (True / False(default))\n'

In [6]:
# df.dropna(axis=1, how='any', inplace=False)
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

## Drop Column

In [7]:
# .drop()
# df.drop(columns=['PHONE_NUMBER', 'EMAIL', 'COMMISSION_PCT'], inplace=False) # remove columns
# df.drop(index=[0, 1], inplace=False) # remove rows

## Fill Null Values

In [8]:
comm_mean = round(df['COMMISSION_PCT'].mean(), 2)
comm_median = df['COMMISSION_PCT'].median()
comm_skew = df['COMMISSION_PCT'].skew()

In [9]:
print(comm_mean)
print(comm_median)
print(comm_skew)

0.22
0.2
0.09661736135041571

In [10]:
mgr_mode = df['MANAGER_ID'].mode()[0]
dep_mode = df['DEPARTMENT_ID'].mode()[0]

In [11]:
print(mgr_mode)
print(dep_mode)

100.0
50.0

In [12]:
df = pd.read_csv('Dataset/Employees.csv')

In [13]:
df.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

In [14]:
# df['COMMISSION_PCT'].fillna(comm_mean, inplace=True)
# df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(comm_mean)
df.fillna({'COMMISSION_PCT':comm_mean}, inplace=True)
df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,0.22,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,0.22,103.0,60.0

In [15]:
df.fillna({'MANAGER_ID':mgr_mode, 'DEPARTMENT_ID':dep_mode}, inplace=True)

## HR Dataset Refresh

In [16]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [17]:
hr.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

### Fill Null Values

In [18]:
mgr_mode = hr['ManagerID'].mode()[0]
hr.fillna({'ManagerID':mgr_mode}, inplace=True)

In [19]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   582 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 163.8+ KB

### Check Duplicate Data

In [20]:
'''
    subset -> accepts column name
    keep -> False, 'first', 'last'
'''

"\n    subset -> accepts column name\n    keep -> False, 'first', 'last'\n"

In [21]:
duplicate_data = hr[hr.duplicated(subset='EmpID')]
# duplicate_data

In [22]:
# emp_id = int(input('Enter employee id: '))
# emp_data = hr[hr['EmpID'] == emp_id]
# emp_data

In [23]:
hr = hr.drop_duplicates(subset='EmpID', keep='last')
# hr.reset_index()
# hr

### Extract specific datatype columns

In [24]:
# select_dtypes([dtype1, dtype2, ..., dtype_n])
numeric_columns = hr.select_dtypes(['int', 'float'])
numeric_columns.columns

Index(['EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID', 'EmpStatusID',
       'DeptID', 'PerfScoreID', 'FromDiversityJobFairID', 'Salary', 'Termd',
       'PositionID', 'Zip', 'ManagerID', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'DaysLateLast30', 'Absences'],
      dtype='object')

In [25]:
numeric_columns.drop(columns=['EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID', 'EmpStatusID',
       'DeptID', 'PerfScoreID', 'FromDiversityJobFairID', 'PositionID', 'ManagerID', 'Termd',
                             'Zip'], inplace=True)

In [26]:
numeric_columns.columns

Index(['Salary', 'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount',
       'DaysLateLast30', 'Absences'],
      dtype='object')

In [27]:
# columns = ['Salary', 'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount', 'DaysLateLast30', 'Absences']

# for col in columns:
#     print(col)
#     skew_data = hr[col].skew()
#     print(skew_data)
#     print('\n')

### Removing Outliers uisng IQR Method

In [28]:
hr['Salary'].skew()

np.float64(3.3061808092400606)

In [29]:
q1 = hr['Salary'].quantile(0.25)
q3 = hr['Salary'].quantile(0.75)

In [30]:
iqr = q3 - q1

In [31]:
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

In [32]:
salary_data = hr[(hr['Salary'] >= lower_bound) & (hr['Salary'] <= upper_bound)]
# salary_data

In [33]:
salary_data['Salary'].skew()

np.float64(0.9483950737390386)

In [34]:
print(f'Q1: {q1}')
print(f'Q3: {q3}')
print(f'IQR: {iqr}')
print(f'Lower Bound: {lower_bound}')
print(f'Upper Bound: {upper_bound}')

Q1: 55501.5
Q3: 72036.0
IQR: 16534.5
Lower Bound: 30699.75
Upper Bound: 96837.75

## Remove Unwanted Data

### Remove Whitespaces

In [35]:
'''
- str.strip()
- Only str column contains whitespaces.
'''

'\n- str.strip()\n- Only str column contains whitespaces.\n'

In [36]:
object_columns = hr.select_dtypes('object')

In [37]:
object_columns = object_columns.drop(columns = ['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date'])

In [38]:
object_columns.columns
columns = ['Employee_Name', 'Position', 'State', 'Gender', 'MaritalDesc',
       'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
       'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource',
       'PerformanceScore']

In [39]:
hr['Gender'].unique()

array(['M ', 'F'], dtype=object)

### check whitespace

In [40]:
def getUniqueValues(dataframe, column_list):
    for col in column_list:
        print(col)
        print('-'*30)
        unique_val = dataframe[col].unique()
        print(unique_val)
        print('\n')

getUniqueValues(hr, columns)

Employee_Name
------------------------------
['Bacong, Alejandro ' 'Baczenski, Rachael  ' 'Barbara, Thomas'
 'Barbossa, Hector' 'Barone, Francesco  A' 'Barton, Nader' 'Bates, Norman'
 'Beak, Kimberly  ' 'Beatrice, Courtney ' 'Becker, Renee' 'Becker, Scott'
 'Bernstein, Sean' 'Biden, Lowan  M' 'Billis, Helen' 'Blount, Dianna'
 'Bondwell, Betsy' 'Booth, Frank' 'Boutwell, Bonalyn' 'Bozzi, Charles'
 'Brill, Donna' 'Brown, Mia' 'Buccheri, Joseph  ' 'Bugali, Josephine '
 'Bunbury, Jessica' 'Burke, Joelle' 'Burkett, Benjamin ' 'Cady, Max '
 'Candie, Calvin' 'Carabbio, Judith' 'Carey, Michael  ' 'Carr, Claudia  N'
 'Carter, Michelle ' 'Chace, Beatrice ' 'Champaigne, Brian' 'Chan, Lin'
 'Chang, Donovan  E' 'Chigurh, Anton' 'Chivukula, Enola'
 'Cierpiszewski, Caroline  ' 'Clayton, Rick' 'Cloninger, Jennifer'
 'Close, Phil' 'Clukey, Elijian' 'Cockel, James' 'Cole, Spencer'
 'Corleone, Michael' 'Corleone, Vito' 'Cornett, Lisa ' 'Costello, Frank'
 'Crimmings,   Jean' 'Cross, Noah' 'Daneault, Lynn' 'Daniele, Ann  '
 "Darson, Jene'ya " 'Davis, Daniel' 'Dee, Randy' 'DeGweck,  James'
 'Del Bosque, Keyla' 'Delarge, Alex' 'Demita, Carla' 'Desimone, Carl '
 'DeVito, Tommy' 'Dickinson, Geoff ' 'Dietrich, Jenna  ' 'DiNocco, Lily '
 'Dobrin, Denisa  S' 'Dolan, Linda' 'Dougall, Eric' 'Driver, Elle'
 'Dunn, Amy  ' 'Dunne, Amy' 'Eaton, Marianne' 'Engdahl, Jean'
 'England, Rex' 'Erilus, Angela' 'Estremera, Miguel' 'Evensen, April'
 'Exantus, Susan' 'Faller, Megan ' 'Fancett, Nicole' 'Ferguson, Susan'
 'Fernandes, Nilson  ' 'Fett, Boba' 'Fidelia,  Libby'
 'Fitzpatrick, Michael  J' 'Foreman, Tanya' 'Forrest, Alex' 'Foss, Jason'
 'Foster-Baker, Amy' 'Fraval, Maruk ' 'Galia, Lisa' 'Garcia, Raul'
 'Gaul, Barbara' 'Gentry, Mildred' 'Gerke, Melisa' 'Gill, Whitney  '
 'Gilles, Alex' 'Girifalco, Evelyn' 'Givens, Myriam' 'Goble, Taisha'
 'Goeth, Amon' 'Gold, Shenice  ' 'Gonzalez, Cayo' 'Gonzalez, Juan'
 'Gonzalez, Maria' 'Good, Susan' 'Gordon, David' 'Gosciminski, Phylicia  '
 'Goyal, Roxana' 'Gray, Elijiah  ' 'Gross, Paula' 'Gruber, Hans'
 'Guilianno, Mike' 'Handschiegl, Joanne' 'Hankard, Earnest'
 'Harrington, Christie ' 'Harrison, Kara' 'Heitzman, Anthony'
 'Hendrickson, Trina' 'Hitchcock, Alfred' 'Homberger, Adrienne  J'
 'Horton, Jayne' 'Houlihan, Debra' 'Howard, Estelle' 'Hudson, Jane'
 'Hunts, Julissa' 'Hutter, Rosalie' 'Huynh, Ming' 'Immediato, Walter'
 'Ivey, Rose ' 'Jackson, Maryellen' 'Jacobi, Hannah  ' 'Jeannite, Tayana'
 'Jhaveri, Sneha  ' 'Johnson, George' 'Johnson, Noelle ' 'Johnston, Yen'
 'Jung, Judy  ' 'Kampew, Donysha' 'Keatts, Kramer '
 'Khemmich, Bartholemew' 'King, Janet' 'Kinsella, Kathleen  '
 'Kirill, Alexandra  ' 'Knapp, Bradley  J' 'Kretschmer, John'
 'Kreuger, Freddy' 'Lajiri,  Jyoti' 'Landa, Hans' 'Langford, Lindsey'
 'Langton, Enrico' 'LaRotonda, William  ' 'Latif, Mohammed' 'Le, Binh'
 'Leach, Dallas' 'LeBlanc, Brandon  R' 'Lecter, Hannibal'
 'Leruth, Giovanni' 'Liebig, Ketsia' 'Linares, Marilyn ' 'Linden, Mathew'
 'Lindsay, Leonara ' 'Lundy, Susan' 'Lunquist, Lisa' 'Lydon, Allison'
 'Lynch, Lindsay' 'MacLennan, Samuel' 'Mahoney, Lauren  '
 'Manchester, Robyn' 'Mancuso, Karen' 'Mangal, Debbie' 'Martin, Sandra'
 'Maurice, Shana' "Carthy, B'rigit" 'Mckenna, Sandy' 'McKinzie, Jac'
 'Meads, Elizabeth' 'Medeiros, Jennifer' 'Miller, Brannon' 'Miller, Ned'
 'Monkfish, Erasumus' 'Monroe, Peter' 'Monterro, Luisa' 'Moran, Patrick'
 'Morway, Tanya' 'Motlagh,  Dawn' 'Moumanil, Maliki ' 'Myers, Michael'
 'Navathe, Kurt' 'Ndzi, Colombui' 'Ndzi, Horia' 'Newman, Richard '
 'Ngodup, Shari ' 'Nguyen, Dheepa' 'Nguyen, Lei-Ming' 'Nowlan, Kristie'
 "O'hare, Lynn" 'Oliver, Brooke ' 'Onque, Jasmine' 'Osturnka, Adeel'
 'Owad, Clinton' 'Ozark, Travis' 'Panjwani, Nina' 'Patronick, Lucas'
 'Pearson, Randall' 'Smith, Martin' 'Pelletier, Ermine' 'Perry, Shakira'
 'Peters, Lauren' 'Peterson, Ebonee  ' 'Petingill, Shana  '
 'Petrowsky, Thelma' 'Pham, Hong' 'Pitt, Brad ' 'Potts, Xana'
 'Power, Morissa' 'Punjabhi, Louis  ' 'Purinton, Janine' 'Quinn, Sean'
 'Rachael, Maggie' 'Rarrick, Quinn' 'Ren, Kylo' 'Rhoads, Thomas'
 'Rivera, Haley  ' 'Roberson, May' 'Robertson, Peter' 'Robinson, Alain  '
 'Robinson, Cherly' 'Robinson, Elias' 'Roby, Lori ' 'Roehrich, Bianca'
 'Roper, Katie' 'Rose, Ashley  ' 'Rossetti, Bruno' 'Roup,Simon'
 'Ruiz, Ricardo' 'Saada, Adell' 'Saar-Beckles, Melinda' 'Sadki, Nore  '
 'Sahoo, Adil' 'Salter, Jason' 'Sander, Kamrin' 'Sewkumar, Nori'
 'Shepard, Anita ' 'Shields, Seffi' 'Simard, Kramer' 'Singh, Nan '
 'Sloan, Constance' 'Smith, Joe' 'Smith, John' 'Smith, Leigh Ann'
 'Smith, Sade' 'Soto, Julia ' 'Soze, Keyser' 'Sparks, Taylor  '
 'Spirea, Kelley' 'Squatrito, Kristen' 'Stanford,Barbara  M'
 'Stansfield, Norman' 'Steans, Tyrone  ' 'Stoica, Rick' 'Strong, Caitrin'
 'Sullivan, Kissy ' 'Sullivan, Timothy' 'Sutwell, Barbara' 'Szabo, Andrew'
 'Tannen, Biff' 'Tavares, Desiree  ' 'Tejeda, Lenora ' 'Terry, Sharlene '
 'Theamstern, Sophia' 'Thibaud, Kenneth' 'Tippett, Jeanette'
 'Torrence, Jack' 'Trang, Mei' 'Tredinnick, Neville ' 'True, Edward'
 'Trzeciak, Cybil' 'Turpin, Jumil' 'Valentin,Jackie' 'Veera, Abdellah '
 'Vega, Vincent' 'Villanueva, Noah' 'Voldemort, Lord' 'Volk, Colleen'
 'Von Massenbach, Anna' 'Walker, Roger' 'Wallace, Courtney  E'
 'Wallace, Theresa' 'Wang, Charlie' 'Warfield, Sarah' 'Whittier, Scott'
 'Wilber, Barry' 'Wilkes, Annie' 'Williams, Jacquelyn  '
 'Winthrop, Jordan  ' 'Wolk, Hang  T' 'Woodson, Jason'
 'Ybarra, Catherine ' 'Zamora, Jennifer' 'Zhou, Julia' 'Zima, Colleen'
 'Adinolfi, Wilson  K' 'Ait Sidi, Karthikeyan   ' 'Akinkuolie, Sarah'
 'Alagbe,Trina' 'Anderson, Carol ' 'Anderson, Linda  ' 'Andreola, Colby'
 'Athwal, Sam' 'Bachiochi, Linda']


Position
------------------------------
['IT Support' 'Production Technician I' 'Data Analyst'
 'Production Technician II' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'Software Engineer' 'Sr. DBA' 'BI Director' 'Director of Operations'
 'Sr. Network Engineer' 'Sales Manager' 'BI Developer'
 'IT Manager - Support' 'Network Engineer' 'IT Director'
 'Director of Sales' 'Administrative Assistant' 'President & CEO'
 'Senior BI Developer' 'Shared Services Manager' 'IT Manager - Infra'
 'Principal Data Architect' 'Data Architect' 'IT Manager - DB'
 'Data Analyst ' 'CIO']


State
------------------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']


Gender
------------------------------
['M ' 'F']


MaritalDesc
------------------------------
['Divorced' 'Married' 'Single' 'Separated' 'Widowed']


CitizenDesc
------------------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']


HispanicLatino
------------------------------
['No' 'Yes' 'no' 'yes']


RaceDesc
------------------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']


TermReason
------------------------------
['N/A-StillEmployed' 'Another position' 'unhappy' 'attendance'
 'performance' 'career change' 'Learned that he is a gangster' 'retiring'
 'relocation out of area' 'more money' 'military' 'no-call, no-show'
 'hours' 'Fatal attraction' 'maternity leave - did not return'
 'return to school' 'medical issues' 'gross misconduct']


EmploymentStatus
------------------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']


Department
------------------------------
['IT/IS' 'Production       ' 'Admin Offices' 'Sales'
 'Software Engineering' 'Executive Office']


ManagerName
------------------------------
['Peter Monroe' 'David Stanley' 'Kissy Sullivan' 'Simon Roup'
 'Kelley Spirea' 'Michael Albert' 'Elijiah Gray' 'Webster Butler'
 'Amy Dunn' 'Ketsia Liebig' 'Brannon Miller' 'Brandon R. LeBlanc'
 'Janet King' 'John Smith' 'Jennifer Zamora' 'Alex Sweetwater'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']


RecruitmentSource
------------------------------
['Indeed' 'Diversity Job Fair' 'Google Search' 'On-line Web application'
 'Employee Referral' 'LinkedIn' 'CareerBuilder' 'Website' 'Other']


PerformanceScore
------------------------------
['Fully Meets' 'Exceeds' 'Needs Improvement' 'PIP']

#### Remove whitespace

In [41]:
'''
Syntax
-------
col_name.str.strip()
'''

'\nSyntax\n-------\ncol_name.str.strip()\n'

In [42]:
def removeWhiteSpaces(dataframe, column_list):
    for col in column_list:
        dataframe[col] = dataframe[col].str.strip()

    print('Whitespace removed.')

In [43]:
hr['Department'] = hr['Department'].str.strip()

In [44]:
removeWhiteSpaces(hr, columns)

Whitespace removed.

### Remove unwated data

In [45]:
'''
- str.replace(find, replace_value, regex=True/False)
'''
hr['Employee_Name'] = hr['Employee_Name'].str.replace(',', '', regex=False)

In [46]:
# hr['Employee_Name'].str.replace(r'[^a-zA-Z]', ' ', regex=True)

In [47]:
'''
Pattern of Regular Expressions
-------------------------------------
\d -> Digits
\s -> whitespaces
\w -> words
+ -> One or more
* -> zero or more

sub(pattern, replace_value, data) -> remove data
findall(pattern, data) -> find and extract data
'''
import re # regular expression

In [48]:
text = '   Hello   !!   contact us : 54321678  abc@gmail.com   def123@gmail.com 1123345####.'

In [49]:
remove_space = re.sub(r'\s+', ' ', text)
remove_space.strip()

'Hello !! contact us : 54321678 abc@gmail.com def123@gmail.com 1123345####.'

In [50]:
remove_val = re.sub(r'[!#]', '', remove_space)
remove_val

' Hello  contact us : 54321678 abc@gmail.com def123@gmail.com 1123345.'

In [51]:
remove_email = re.sub(r'\w+@\w+.\w+', '', remove_space)
remove_email

' Hello !! contact us : 54321678   1123345####.'

In [52]:
## find email
email = re.findall(r'\w+@\w+.\w+', text)
email

['abc@gmail.com', 'def123@gmail.com']

## Convert Datatypes

In [ ]:
# astype(datatype) -> int, str, float, boolean
# datetime

In [70]:
# hr.info()

In [58]:
hr['ManagerID'] = hr['ManagerID'].astype(int)

In [ ]:
'''
DateTime -> YYYY-MM-DD

-> pd.to_datetime(col_name, format/dayfirst)

format
-------
'%d.%m.%y' (default)
'%d-%m-%y'
'mixed'

dayfirst
--------
True
False (default)
'''

In [67]:
def convertDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')
    print('Date converted..')

In [61]:
date_columns = ['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date']

In [63]:
hr['DOB'] = pd.to_datetime(hr['DOB'], format='mixed')

In [68]:
convertDateTime(hr, 'DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date')

Date converted..

### Store data to new file

In [73]:
hr.to_csv('cleaned_hr.csv', index=False)
hr.to_excel('cleaned_hr.xlsx', index=False)
hr.to_json('cleaned_hr.json', indent=4)

In [74]:
hr_csv = pd.read_csv('cleaned_hr.csv')
hr_excel = pd.read_excel('cleaned_hr.xlsx')

In [76]:
# hr_excel.info()

In [78]:
# hr_csv.info()

In [81]:
# Question 5: Text Operations / ID Masking 
# Find all employees who work under the Manager "Kissy Sullivan" and have been late at least 
# once (DaysLateLast30 is greater than 0).

emp_mgr = hr[(hr['ManagerName'] == 'Kissy Sullivan') & (hr['DaysLateLast30'] > 0)]
emp_mgr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
72,Cole Spencer,10292,0,0,1,4,5,2,0,59144,...,Kissy Sullivan,20,LinkedIn,Needs Improvement,2.00,3,0,2016-05-01,5,16
224,O'hare Lynn,10303,0,0,0,4,5,1,0,52674,...,Kissy Sullivan,20,LinkedIn,PIP,2.33,2,0,2018-03-09,6,3